name: textstyle_extensions
description: Syntactic sugar for easily modifying TextStyles.
version: 0.0.1
homepage: https://github.com/gskinnerTeam/flutter-textstyle-extensions

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
